# Generated by Django 6.0.5 on 2026-05-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('name', models.CharField(max_length=200, verbose_name='Certificate Name')),
                ('issuer', models.CharField(max_length=200, verbose_name='Issuer')),
                ('date', models.CharField(blank=True, default='', max_length=100, verbose_name='Date')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('institution', models.CharField(max_length=200, verbose_name='Institution')),
                ('degree', models.CharField(max_length=200, verbose_name='Degree')),
                ('field', models.CharField(blank=True, default='', max_length=200, verbose_name='Field of Study')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='Location')),
                ('start_date', models.CharField(max_length=100, verbose_name='Start Date')),
                ('end_date', models.CharField(blank=True, default='', max_length=100, verbose_name='End Date')),
                ('gpa', models.CharField(blank=True, default='', max_length=50, verbose_name='GPA')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('company', models.CharField(max_length=200, verbose_name='Company')),
                ('position', models.CharField(max_length=200, verbose_name='Position')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='Location')),
                ('start_date', models.CharField(max_length=100, verbose_name='Start Date')),
                ('end_date', models.CharField(blank=True, default='', max_length=100, verbose_name='End Date')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('bullet_points', models.TextField(blank=True, default='', verbose_name='Bullet Points (one per line)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='experience/', verbose_name='Company Image')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('name', models.CharField(blank=True, default='', help_text='This is variable of the setting.', max_length=254, verbose_name='Name')),
                ('description', models.CharField(blank=True, default='', max_length=254, verbose_name='Description')),
                ('parameter', models.TextField(blank=True, default='', verbose_name='Parameter')),
            ],
            options={
                'verbose_name': 'General Setting',
                'verbose_name_plural': 'General Settings',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('title', models.CharField(max_length=200, verbose_name='Project Title')),
                ('category', models.CharField(blank=True, default='', max_length=100, verbose_name='Category')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Project Image')),
                ('url', models.URLField(blank=True, default='', verbose_name='Project URL')),
                ('technologies', models.CharField(blank=True, default='', max_length=500, verbose_name='Technologies Used')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('name', models.CharField(max_length=100, verbose_name='Skill Name')),
                ('percentage', models.IntegerField(default=0, verbose_name='Percentage')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('platform', models.CharField(max_length=100, verbose_name='Platform')),
                ('url', models.URLField(verbose_name='URL')),
                ('icon_class', models.CharField(help_text='e.g., bi bi-github', max_length=100, verbose_name='Icon CSS Class')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ('order',),
            },
        ),
    ]
