# Generated by Django 6.0.5 on 2026-05-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ('order',), 'verbose_name': 'Sertifika', 'verbose_name_plural': 'Sertifikalar'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ('order',), 'verbose_name': 'Eğitim', 'verbose_name_plural': 'Eğitimler'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ('order',), 'verbose_name': 'İş Deneyimi', 'verbose_name_plural': 'İş Deneyimleri'},
        ),
        migrations.AlterModelOptions(
            name='generalsetting',
            options={'ordering': ('name',), 'verbose_name': 'Genel Ayar', 'verbose_name_plural': 'Genel Ayarlar'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('order',), 'verbose_name': 'Proje', 'verbose_name_plural': 'Projeler'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('category', 'order'), 'verbose_name': 'Beceri', 'verbose_name_plural': 'Beceriler'},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ('order',), 'verbose_name': 'Sosyal Medya Bağlantısı', 'verbose_name_plural': 'Sosyal Medya Bağlantıları'},
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('programlama', 'Programlama Dilleri'), ('bulut', 'Bulut & DevOps'), ('ag_guvenlik', 'Ağ & Güvenlik'), ('veritabani', 'Veritabanı & Araçlar')], default='programlama', max_length=50, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issuer',
            field=models.CharField(max_length=200, verbose_name='Veren Kurum'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Sertifika Adı'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='education',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi'),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=200, verbose_name='Derece'),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Bitiş Tarihi'),
        ),
        migrations.AlterField(
            model_name='education',
            name='field',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Bölüm'),
        ),
        migrations.AlterField(
            model_name='education',
            name='gpa',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='GNO'),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(max_length=200, verbose_name='Kurum'),
        ),
        migrations.AlterField(
            model_name='education',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Konum'),
        ),
        migrations.AlterField(
            model_name='education',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.CharField(max_length=100, verbose_name='Başlangıç Tarihi'),
        ),
        migrations.AlterField(
            model_name='education',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='bullet_points',
            field=models.TextField(blank=True, default='', verbose_name='Maddeler (her satıra bir madde)'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(max_length=200, verbose_name='Şirket'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Bitiş Tarihi'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='experience/', verbose_name='Şirket Görseli'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Konum'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position',
            field=models.CharField(max_length=200, verbose_name='Pozisyon'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.CharField(max_length=100, verbose_name='Başlangıç Tarihi'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Bu ayarın ne işe yaradığını açıklar.', max_length=254, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Bu ayarın değişken adıdır.', max_length=254, verbose_name='Değişken Adı'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='parameter',
            field=models.TextField(blank=True, default='', help_text='Bu ayarın değeridir.', verbose_name='Değer'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('cloud', 'Bulut'), ('web', 'Web'), ('ai', 'Yapay Zeka')], default='', max_length=100, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Proje Görseli'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Kullanılan Teknolojiler'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Proje Başlığı'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, default='', verbose_name='Proje Bağlantısı'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Beceri Adı'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='percentage',
            field=models.IntegerField(default=0, verbose_name='Yüzde (%)'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon_class',
            field=models.CharField(help_text='Örn: bi bi-github', max_length=100, verbose_name='İkon CSS Sınıfı'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.URLField(verbose_name='Bağlantı'),
        ),
    ]
