# Generated by Django 6.0.5 on 2026-05-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_certificate_options_alter_education_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('title', models.CharField(max_length=100, verbose_name='Menü Başlığı')),
                ('url', models.CharField(help_text='Örn: /#about veya /contact/', max_length=200, verbose_name='Hedef URL / Çapa (Anchor)')),
                ('icon_class', models.CharField(help_text='Örn: bi bi-person navicon', max_length=100, verbose_name='İkon Sınıfı (Bootstrap Icons)')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama Sırası')),
            ],
            options={
                'verbose_name': 'Menü Bağlantısı',
                'verbose_name_plural': 'Menü Bağlantıları',
                'ordering': ('order',),
            },
        ),
    ]
