# Generated by Django 6.0.5 on 2026-05-21 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_navbarlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(help_text='Örn: cloud, web, ai', max_length=100, unique=True, verbose_name='Slug (Url Uyumlu Ad)')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Proje Kategorisi',
                'verbose_name_plural': 'Proje Kategorileri',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('icon_class', models.CharField(default='bi bi-gear', help_text='Örn: bi bi-code-slash', max_length=100, verbose_name='İkon Sınıfı')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Beceri Kategorisi',
                'verbose_name_plural': 'Beceri Kategorileri',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='project',
            name='category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.projectcategory', verbose_name='Dinamik Kategori'),
        ),
        migrations.AddField(
            model_name='skill',
            name='category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.skillcategory', verbose_name='Dinamik Kategori'),
        ),
    ]
