# Generated by Django 6.0.5 on 2026-05-21 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_projectcategory_skillcategory_project_category_fk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='category_fk',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='category_fk',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.projectcategory', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.skillcategory', verbose_name='Kategori'),
        ),
    ]
